In [42]:
import tensorflow as tf
from tensorflow.keras.preprocessing.sequence import TimeseriesGenerator
import numpy as np
from sklearn.model_selection import train_test_split

In [48]:
X = np.arange(100)
X = np.vstack((X, np.arange(200, 300))).T
y = np.arange(500, 600).reshape(-1, 1)
# x_train, y_train, x_test, y_test = train_test_split(X, y, test_size=0.2)
TEST_SIZE = 0.2
time_train = TimeseriesGenerator(X, y, length=5, end_index=round(X.shape[0] * TEST_SIZE))
time_test = TimeseriesGenerator(X, y, length=5, start_index=round(X.shape[0] * TEST_SIZE))
xg, yg = time_train[0]
xt, yt = time_test[0]

print(xg)
print(yg)
print(xt)
print(yt)

[[[  0 200]
  [  1 201]
  [  2 202]
  [  3 203]
  [  4 204]]

 [[  1 201]
  [  2 202]
  [  3 203]
  [  4 204]
  [  5 205]]

 [[  2 202]
  [  3 203]
  [  4 204]
  [  5 205]
  [  6 206]]

 [[  3 203]
  [  4 204]
  [  5 205]
  [  6 206]
  [  7 207]]

 [[  4 204]
  [  5 205]
  [  6 206]
  [  7 207]
  [  8 208]]

 [[  5 205]
  [  6 206]
  [  7 207]
  [  8 208]
  [  9 209]]

 [[  6 206]
  [  7 207]
  [  8 208]
  [  9 209]
  [ 10 210]]

 [[  7 207]
  [  8 208]
  [  9 209]
  [ 10 210]
  [ 11 211]]

 [[  8 208]
  [  9 209]
  [ 10 210]
  [ 11 211]
  [ 12 212]]

 [[  9 209]
  [ 10 210]
  [ 11 211]
  [ 12 212]
  [ 13 213]]

 [[ 10 210]
  [ 11 211]
  [ 12 212]
  [ 13 213]
  [ 14 214]]

 [[ 11 211]
  [ 12 212]
  [ 13 213]
  [ 14 214]
  [ 15 215]]

 [[ 12 212]
  [ 13 213]
  [ 14 214]
  [ 15 215]
  [ 16 216]]

 [[ 13 213]
  [ 14 214]
  [ 15 215]
  [ 16 216]
  [ 17 217]]

 [[ 14 214]
  [ 15 215]
  [ 16 216]
  [ 17 217]
  [ 18 218]]

 [[ 15 215]
  [ 16 216]
  [ 17 217]
  [ 18 218]
  [ 19 219]]]
[[505]
 

In [45]:
X.shape[0]



100